version: "3"

networks:
  prod:

volumes:
  document_accounting:
  www-html:
  etc-letsencrypt:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - document_accounting_db
      - app
      - frontend
    restart: always
    networks:
      - prod

  document_accounting_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=ivan
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=document_accounting_db
    volumes:
      - document_accounting:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - prod

  app:
    restart: always
    build: ./DocumentAccounting2
    ports:
      - "8080:8080"
    depends_on:
      - document_accounting_db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://document_accounting_db:5432/document_accounting_db"
      JAVA_OPTS: "-Xmx512m"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - prod

  frontend:
    image: frontend:0.0.1
    build:
      context: ./frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    networks:
      - prod
