volumes:
  database-volume:

services:
  database:
    image: postgres
    container_name: database
    restart: always
    volumes:
      - database-volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    build: .
    container_name: backend
    ports:
      - '8080:8080'
    env_file: ./.env
    environment:
      - NODE_ENV=development
      - DB_HOST=database
      - DB_USER=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$POSTGRES_DB
      - DB_PORT=$POSTGRES_PORT
    depends_on:
      database:
        condition: service_healthy
