POST http://localhost:8080/api/auth/sign-up
Content-Type: application/json

{
  "name": "elena",
  "lastname": "korch",
  "username": "korchel",
  "email": "some@email.com",
  "password": "foobar"
}


###
POST http://localhost:8080/api/auth/sign-in
Content-Type: application/json

{
  "username": "korchel",
  "password": "foobar"
}

###
GET http://localhost:8080/api/users
Content-Type: application/json
